# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 15:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160401_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default=datetime.datetime(2016, 4, 1, 15, 29, 36, 246949, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
