# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160404_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
