# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160404_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
