# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20160408_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=200, unique=True),
        ),
    ]
